name: ci

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --force

      - name: Set database credentials as environment variables
        env:
          PG_HOST: localhost
          PG_PORT: 5432
          PG_DB: mydatabase
          PG_USER: myuser
          PG_PASS: mypassword
          MINIO_ENDPOINT: 127.0.0.1
          MINIO_PORT: 9000
          MINIO_ACCESS_KEY: minio_access_key
          MINIO_SECRET_KEY: minio_secret_key
        run: |
          echo "export PG_HOST=$PG_HOST" >> .env
          echo "export PG_PORT=$PG_PORT" >> .env
          echo "export PG_DB=$PG_DB" >> .env
          echo "export PG_USER=$PG_USER" >> .env
          echo "export PG_PASS=$PG_PASS" >> .env
          echo "export MINIO_ENDPOINT=$MINIO_ENDPOINT" >> .env
          echo "export MINIO_PORT=$MINIO_PORT" >> .env
          echo "export MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY" >> .env
          echo "export MINIO_SECRET_KEY=$MINIO_SECRET_KEY" >> .env

      - name: Build
        run: yarn build

      - name: Run app
        run: |
          yarn start:prod & 
          sleep 5

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: setup-node

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push to Prod
        if: github.ref_name == 'main'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:latest
          
      - name: Build and push to Dev
        if: github.ref_name == 'dev'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ github.event.repository.name }}:dev
